# Generated by Django 3.0.4 on 2020-03-22 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200320_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='toys',
            field=models.ManyToManyField(to='main_app.Toy'),
        ),
    ]
